name: '@codex_bot notifier'
description: 'Send notification to chat from @codex_bot'

inputs:
  webhook:
    description: 'Endpoint for sending message to chat'
    required: true

  message:
    description: 'Message text'
    required: true

  parse_mode:
    description: 'Mode for parsing entities in the message text'
    required: false

  disable_web_page_preview:
    description: 'Disables link previews for links in this message'
    required: false

outputs:
  response-body:
    description: 'Response message'

  response-code:
    description: 'Response code'

runs:
  using: 'node12'
  main: 'dist/index.js'