name: 'Get package info'
description: 'Get package name and version'

inputs:
  path:
    description: 'Path to package.json file'
    required: false
    default: ./

outputs:
  name:
    description: 'Package name'

  version:
    description: 'Package version'

runs:
  using: 'node12'
  main: 'dist/index.js'